aws:
  enabled: false
azure:
  enabled: false
cf:
  accounts:
  enabled: false
credentials:
  challengeDestructiveActionsEnvironments: default
  primaryAccountTypes: default
default:
  account:
    env: minikube



google:
  enabled: false
kubernetes:
  enabled: false

dockerRegistry:
  enabled: false

redis:
  connection: redis://10.20.70.102:6379
server:
  port: 7002
services:
  front50:
    baseUrl: http://10.20.70.102:8080
udf:
  enabled: false
