redis:
  connection: redis://${IP}:6379
server:
  port: 8084
services:
  clouddriver:
    baseUrl: http://${IP}:7002
  deck:
    baseUrl: http://${IP}:9000
  front50:
    baseUrl: http://${IP}:8080
  orca:
    baseUrl: http://${IP}:8083
  igor:
    enabled: true
    baseUrl: http://${IP}:8088
  rosco:
    enabled: true
    baseUrl: http://${IP}:8087