server:
  port: 8088

jenkins:
  enabled: true
  masters:
    - name: jenkins
      address: http://10.20.70.102:8888/
      username: jenkins
      password: jenkins

travis:
  enabled: false

dockerRegistry:
  enabled: true

redis:
  connection: redis://10.20.70.102:6379

services:
  clouddriver:
    baseUrl: http://10.20.70.102:7002
  echo:
    baseUrl: http://10.20.70.102:8089