server:
  port: 8088

jenkins:
  enabled: true
  masters:
    - name: jenkins
      address: http://${IP}:8888/
      username: jenkins
      password: jenkins

travis:
  enabled: false

dockerRegistry:
  enabled: true

redis:
  connection: redis://${IP}:6379

services:
  clouddriver:
    baseUrl: http://${IP}:7002
  echo:
    baseUrl: http://${IP}:8089