bakery:
  allowMissingPackageInstallation: true
  baseUrl: http://10.20.70.102:8087
  extractBuildDetails: true
  propagateCloudProviderType: true
default:
  bake:
    account: minikube
  securityGroups: null
  vpc:
    securityGroups: null
echo:
  baseUrl: 8089
  enabled: false
flex:
  baseUrl: http://not-a-host
front50:
  baseUrl: http://10.20.70.102:8080
igor:
  enabled: true
  baseUrl: http://10.20.70.102:8088
kato:
  baseUrl: http://10.20.70.102:7002
mort:
  baseUrl: http://10.20.70.102:7002
oort:
  baseUrl: http://10.20.70.102:7002
redis:
  connection: redis://10.20.70.102:6379
server:
  port: 8083
services:
  orca:
    timezone: west
tasks:
  executionWindow:
    timezone: west
tide:
  baseUrl: http://not-a-host
  enabled: false
